### ISSUE TITLE
Yaml configuration support

### ISSUE THREAD

**Issue by MrHash** [MrHash/TaskMachine#4]
```yaml
version: "0.1"
tasks:
  hello:
    handler: SomeLibrary\DoSomething
  process:
    handler: TaskMachine\ProcessHandler
    validate:
      "input.command": string
      "input.mode": bool
      "output.exit_code": integer
  goodbye:
    handler: MyProject\MyHandler
  fail:
    handler: FailHandler

pipelines:
  do-it:
    hello: ~
    process:
      input:
        switch: true
    goodbye: ~

machines:
  reverse-it:
    goodbye:
      initial: true
      map:
        "input.what": ever
        "output.some": thing
      transition: process
    process:
      input:
        switch: true
      transition: 
        "output.result": hello
        "!output.result": fail
    hello:
      final: true
    fail:
      final: true
```
